//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        public Almacen()
        {
            this.AlmacenUbicacion = new HashSet<AlmacenUbicacion>();
        }
    
        public decimal idAlmacen { get; set; }
        public decimal idTipoAlmacen { get; set; }
        public decimal idEmpresa { get; set; }
        public decimal idSucursal { get; set; }
        public string nombreAlmacen { get; set; }
        public decimal idUsuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool activo { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoAlmacen TipoAlmacen { get; set; }
        public virtual ICollection<AlmacenUbicacion> AlmacenUbicacion { get; set; }
    }
}
