//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    public partial class Articulo
    {
        public Articulo()
        {
            this.ArticuloCaracteristica = new HashSet<ArticuloCaracteristica>();
            this.ArticuloPrecio = new HashSet<ArticuloPrecio>();
        }
    
        public decimal idArticulo { get; set; }
        public decimal idEmpresa { get; set; }
        public decimal idProveedor { get; set; }
        public string sku { get; set; }
        public decimal barcode { get; set; }
        public decimal idTipoArticulo { get; set; }
        public decimal idMarca { get; set; }
        public decimal idColeccion { get; set; }
        public decimal temporada { get; set; }
        public decimal idCategoria { get; set; }
        public decimal idSubCategoria { get; set; }
        public string claveArticulo { get; set; }
        public string descArticulo { get; set; }
        public string nombreArticulo { get; set; }
        public string claveColor { get; set; }
        public string claveTalla { get; set; }
        public decimal idPresentacion { get; set; }
        public decimal cantidadPresentacion { get; set; }
        public string epcPrefijo { get; set; }
        public decimal epcSerie { get; set; }
        public decimal idUsuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool activo { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Coleccion Coleccion { get; set; }
        public virtual Color Color { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Presentacion Presentacion { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual SubCategoria SubCategoria { get; set; }
        public virtual Talla Talla { get; set; }
        public virtual TipoArticulo TipoArticulo { get; set; }
        public virtual ICollection<ArticuloCaracteristica> ArticuloCaracteristica { get; set; }
        public virtual ICollection<ArticuloPrecio> ArticuloPrecio { get; set; }
    }
}
