//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticuloPrecio
    {
        public decimal idArticulo { get; set; }
        public decimal idTipoImporte { get; set; }
        public decimal idEmpresa { get; set; }
        public decimal idDivisa { get; set; }
        public decimal valor { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
        public decimal idUsuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool activo { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Articulo Articulo { get; set; }
        public virtual Divisa Divisa { get; set; }
        public virtual TipoImporte TipoImporte { get; set; }
    }
}
