//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Almacen = new HashSet<Almacen>();
            this.Articulo = new HashSet<Articulo>();
            this.ArticuloPrecio = new HashSet<ArticuloPrecio>();
            this.Caracteristica = new HashSet<Caracteristica>();
            this.Categoria = new HashSet<Categoria>();
            this.Coleccion = new HashSet<Coleccion>();
            this.Color = new HashSet<Color>();
            this.Marca = new HashSet<Marca>();
            this.Mensajeria = new HashSet<Mensajeria>();
            this.Presentacion = new HashSet<Presentacion>();
            this.Proveedor = new HashSet<Proveedor>();
            this.RazonSocial = new HashSet<RazonSocial>();
            this.Sucursal = new HashSet<Sucursal>();
            this.Talla = new HashSet<Talla>();
            this.TipoAlmacen = new HashSet<TipoAlmacen>();
            this.TipoArticulo = new HashSet<TipoArticulo>();
            this.TipoImporte = new HashSet<TipoImporte>();
            this.TipoSucursal = new HashSet<TipoSucursal>();
            this.TipoUbicacion = new HashSet<TipoUbicacion>();
            this.UsuarioRol = new HashSet<UsuarioRol>();
        }
    
        public decimal idEmpresa { get; set; }
        public string nombreEmpresa { get; set; }
        public decimal idUsuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<Almacen> Almacen { get; set; }
        public virtual ICollection<Articulo> Articulo { get; set; }
        public virtual ICollection<ArticuloPrecio> ArticuloPrecio { get; set; }
        public virtual ICollection<Caracteristica> Caracteristica { get; set; }
        public virtual ICollection<Categoria> Categoria { get; set; }
        public virtual ICollection<Coleccion> Coleccion { get; set; }
        public virtual ICollection<Color> Color { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Marca> Marca { get; set; }
        public virtual ICollection<Mensajeria> Mensajeria { get; set; }
        public virtual ICollection<Presentacion> Presentacion { get; set; }
        public virtual ICollection<Proveedor> Proveedor { get; set; }
        public virtual ICollection<RazonSocial> RazonSocial { get; set; }
        public virtual ICollection<Sucursal> Sucursal { get; set; }
        public virtual ICollection<Talla> Talla { get; set; }
        public virtual ICollection<TipoAlmacen> TipoAlmacen { get; set; }
        public virtual ICollection<TipoArticulo> TipoArticulo { get; set; }
        public virtual ICollection<TipoImporte> TipoImporte { get; set; }
        public virtual ICollection<TipoSucursal> TipoSucursal { get; set; }
        public virtual ICollection<TipoUbicacion> TipoUbicacion { get; set; }
        public virtual ICollection<UsuarioRol> UsuarioRol { get; set; }
    }
}
