//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.FacturaConcepto = new HashSet<FacturaConcepto>();
        }
    
        public decimal idFactura { get; set; }
        public string archivoPDF { get; set; }
        public string archivoXML { get; set; }
        public Nullable<decimal> idRuta { get; set; }
        public string serie { get; set; }
        public string foio { get; set; }
        public System.DateTime fechaFactura { get; set; }
        public string moneda { get; set; }
        public decimal subtotal { get; set; }
        public Nullable<decimal> tasaIVA { get; set; }
        public Nullable<decimal> importeIVA { get; set; }
        public decimal total { get; set; }
        public string emisorRfc { get; set; }
        public string emisorNombre { get; set; }
        public string emisorCalle { get; set; }
        public string emisorNoExterior { get; set; }
        public string emisorNoInterior { get; set; }
        public string emisorColonia { get; set; }
        public string emisorLocalidad { get; set; }
        public string emisorMunicipio { get; set; }
        public string emisorEstado { get; set; }
        public string emisorPais { get; set; }
        public Nullable<decimal> emisorCP { get; set; }
        public string receptorRfc { get; set; }
        public string receptorNombre { get; set; }
        public string receptorCalle { get; set; }
        public string receptorNoExterior { get; set; }
        public string receptorNoInterior { get; set; }
        public string receptorColonia { get; set; }
        public string receptorLocalidad { get; set; }
        public string receptorMunicipio { get; set; }
        public string receptorEstado { get; set; }
        public string receptorPais { get; set; }
        public Nullable<decimal> receptorCP { get; set; }
        public decimal idUsuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool activo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Ruta Ruta { get; set; }
        public virtual ICollection<FacturaConcepto> FacturaConcepto { get; set; }
    }
}
