//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaConcepto
    {
        public decimal idFacturaConcepto { get; set; }
        public decimal idFactura { get; set; }
        public decimal cantidad { get; set; }
        public string unidad { get; set; }
        public string descripcion { get; set; }
        public decimal valorUnitario { get; set; }
        public decimal importe { get; set; }
        public decimal idUsuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool activo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
