//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HoondDBEntities : DbContext
    {
        public HoondDBEntities()
            : base("name=HoondDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Empresa> Empresa { get; set; }
        public DbSet<Icono> Icono { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<RolMenu> RolMenu { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<UsuarioProvider> UsuarioProvider { get; set; }
        public DbSet<UsuarioRol> UsuarioRol { get; set; }
        public DbSet<Vista> Vista { get; set; }
        public DbSet<Almacen> Almacen { get; set; }
        public DbSet<AlmacenUbicacion> AlmacenUbicacion { get; set; }
        public DbSet<Articulo> Articulo { get; set; }
        public DbSet<ArticuloCaracteristica> ArticuloCaracteristica { get; set; }
        public DbSet<ArticuloPrecio> ArticuloPrecio { get; set; }
        public DbSet<Caracteristica> Caracteristica { get; set; }
        public DbSet<Categoria> Categoria { get; set; }
        public DbSet<Coleccion> Coleccion { get; set; }
        public DbSet<Color> Color { get; set; }
        public DbSet<Marca> Marca { get; set; }
        public DbSet<Mensajeria> Mensajeria { get; set; }
        public DbSet<Presentacion> Presentacion { get; set; }
        public DbSet<Proveedor> Proveedor { get; set; }
        public DbSet<ProveedorContacto> ProveedorContacto { get; set; }
        public DbSet<RazonSocial> RazonSocial { get; set; }
        public DbSet<SubCategoria> SubCategoria { get; set; }
        public DbSet<Sucursal> Sucursal { get; set; }
        public DbSet<Talla> Talla { get; set; }
        public DbSet<TipoAlmacen> TipoAlmacen { get; set; }
        public DbSet<TipoArticulo> TipoArticulo { get; set; }
        public DbSet<TipoArticuloCaracteristica> TipoArticuloCaracteristica { get; set; }
        public DbSet<TipoImporte> TipoImporte { get; set; }
        public DbSet<TipoSucursal> TipoSucursal { get; set; }
        public DbSet<TipoUbicacion> TipoUbicacion { get; set; }
        public DbSet<Ubicacion> Ubicacion { get; set; }
        public DbSet<UsuarioSucursal> UsuarioSucursal { get; set; }
        public DbSet<ValorCaracteristica> ValorCaracteristica { get; set; }
        public DbSet<ASPStateTempApplications> ASPStateTempApplications { get; set; }
        public DbSet<ASPStateTempSessions> ASPStateTempSessions { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Divisa> Divisa { get; set; }
        public DbSet<Estatus> Estatus { get; set; }
        public DbSet<Provider> Provider { get; set; }
        public DbSet<Ruta> Ruta { get; set; }
        public DbSet<TipoEstatus> TipoEstatus { get; set; }
        public DbSet<TipoLogin> TipoLogin { get; set; }
        public DbSet<TipoPermiso> TipoPermiso { get; set; }
        public DbSet<TipoUsuarioSucursal> TipoUsuarioSucursal { get; set; }
        public DbSet<Factura> Factura { get; set; }
        public DbSet<FacturaConcepto> FacturaConcepto { get; set; }
        public DbSet<LogModificacion> LogModificacion { get; set; }
    
        public virtual int DeleteExpiredSessions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteExpiredSessions");
        }
    }
}
