//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Icono
    {
        public Icono()
        {
            this.Menu = new HashSet<Menu>();
            this.Vista = new HashSet<Vista>();
        }
    
        public decimal idIcono { get; set; }
        public string descIcono { get; set; }
        public string claseIcono { get; set; }
        public string rutaIcono { get; set; }
        public decimal x { get; set; }
        public decimal y { get; set; }
        public decimal idUsuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool activo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual ICollection<Vista> Vista { get; set; }
    }
}
