//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogModificacion
    {
        public decimal idLogModificacion { get; set; }
        public string tabla { get; set; }
        public decimal id { get; set; }
        public decimal idUsuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string accion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
