//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Menu1 = new HashSet<Menu>();
            this.RolMenu = new HashSet<RolMenu>();
        }
    
        public decimal idMenu { get; set; }
        public Nullable<decimal> idMenu_padre { get; set; }
        public decimal idVista { get; set; }
        public string descMenu { get; set; }
        public string etiqueta { get; set; }
        public decimal orden { get; set; }
        public Nullable<decimal> idIcono { get; set; }
        public decimal idUsuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool activo { get; set; }
    
        public virtual Icono Icono { get; set; }
        public virtual ICollection<Menu> Menu1 { get; set; }
        public virtual Menu Menu2 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Vista Vista { get; set; }
        public virtual ICollection<RolMenu> RolMenu { get; set; }
    }
}
