//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public Proveedor()
        {
            this.Articulo = new HashSet<Articulo>();
            this.Marca = new HashSet<Marca>();
            this.ProveedorContacto = new HashSet<ProveedorContacto>();
            this.RazonSocial = new HashSet<RazonSocial>();
        }
    
        public decimal idProveedor { get; set; }
        public decimal idEmpresa { get; set; }
        public string nombreProveedor { get; set; }
        public decimal idUsuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool activo { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Articulo> Articulo { get; set; }
        public virtual ICollection<Marca> Marca { get; set; }
        public virtual ICollection<ProveedorContacto> ProveedorContacto { get; set; }
        public virtual ICollection<RazonSocial> RazonSocial { get; set; }
    }
}
