//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedorContacto
    {
        public decimal idProveedorContacto { get; set; }
        public decimal idProveedor { get; set; }
        public string nombreContacto { get; set; }
        public string apPaternoContacto { get; set; }
        public string apMaternoContacto { get; set; }
        public string emailContacto { get; set; }
        public string telefonoContacto { get; set; }
        public string dirContactoPais { get; set; }
        public string dirContactoEstado { get; set; }
        public string dirContactoMunicipio { get; set; }
        public Nullable<decimal> dirContactoCP { get; set; }
        public string dirContactoColonia { get; set; }
        public string dirContactoCalle { get; set; }
        public string dirContactoNoExterior { get; set; }
        public string dirContactoNoInterior { get; set; }
        public decimal idUsuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool activo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
