//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RazonSocial
    {
        public decimal idRazonSocial { get; set; }
        public decimal idEmpresa { get; set; }
        public decimal idProveedor { get; set; }
        public string rfc { get; set; }
        public string razonSocial1 { get; set; }
        public string dirRazonSocialPais { get; set; }
        public string dirRazonSocialEstado { get; set; }
        public string dirRazonSocialMunicipio { get; set; }
        public decimal dirRazonSocialCP { get; set; }
        public string dirRazonSocialColonia { get; set; }
        public string dirRazonSocialCalle { get; set; }
        public string dirRazonSocialNoExterior { get; set; }
        public string dirRazonSocialNoInterior { get; set; }
        public decimal idUsuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool activo { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual RazonSocial RazonSocial11 { get; set; }
        public virtual RazonSocial RazonSocial2 { get; set; }
    }
}
