//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategoria
    {
        public SubCategoria()
        {
            this.Articulo = new HashSet<Articulo>();
        }
    
        public decimal idSubCategoria { get; set; }
        public decimal idCategoria { get; set; }
        public string descSubCategoria { get; set; }
        public decimal idUsuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool activo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Articulo> Articulo { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
