//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public Sucursal()
        {
            this.Almacen = new HashSet<Almacen>();
            this.UsuarioSucursal = new HashSet<UsuarioSucursal>();
        }
    
        public decimal idSucursal { get; set; }
        public decimal idEmpresa { get; set; }
        public decimal idTipoSucursal { get; set; }
        public string nombreSucursal { get; set; }
        public string telefonoSucursal { get; set; }
        public string dirSucursalPais { get; set; }
        public string dirSucursalEstado { get; set; }
        public string dirSucursalMunicipio { get; set; }
        public Nullable<decimal> dirSucursalCP { get; set; }
        public string dirSucursalColonia { get; set; }
        public string dirSucursalCalle { get; set; }
        public string dirSucursalNoExterior { get; set; }
        public string dirSucursalNoInterior { get; set; }
        public decimal idUsuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool activo { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Almacen> Almacen { get; set; }
        public virtual TipoSucursal TipoSucursal { get; set; }
        public virtual ICollection<UsuarioSucursal> UsuarioSucursal { get; set; }
    }
}
