//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoArticulo
    {
        public TipoArticulo()
        {
            this.Articulo = new HashSet<Articulo>();
            this.Categoria = new HashSet<Categoria>();
            this.Color = new HashSet<Color>();
            this.Presentacion = new HashSet<Presentacion>();
            this.Talla = new HashSet<Talla>();
            this.TipoArticuloCaracteristica = new HashSet<TipoArticuloCaracteristica>();
        }
    
        public decimal idTipoArticulo { get; set; }
        public decimal idEmpresa { get; set; }
        public decimal idMarca { get; set; }
        public string descTipoArticulo { get; set; }
        public decimal idUsuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool activo { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Articulo> Articulo { get; set; }
        public virtual ICollection<Categoria> Categoria { get; set; }
        public virtual ICollection<Color> Color { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual ICollection<Presentacion> Presentacion { get; set; }
        public virtual ICollection<Talla> Talla { get; set; }
        public virtual ICollection<TipoArticuloCaracteristica> TipoArticuloCaracteristica { get; set; }
    }
}
