//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public Ubicacion()
        {
            this.AlmacenUbicacion = new HashSet<AlmacenUbicacion>();
            this.Ubicacion1 = new HashSet<Ubicacion>();
        }
    
        public decimal idUbicacion { get; set; }
        public decimal idTipoUbicacion { get; set; }
        public Nullable<decimal> idUbicacionPadre { get; set; }
        public decimal idUsuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool activo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<AlmacenUbicacion> AlmacenUbicacion { get; set; }
        public virtual TipoUbicacion TipoUbicacion { get; set; }
        public virtual ICollection<Ubicacion> Ubicacion1 { get; set; }
        public virtual Ubicacion Ubicacion2 { get; set; }
    }
}
