//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Empresa = new HashSet<Empresa>();
            this.Icono = new HashSet<Icono>();
            this.Menu = new HashSet<Menu>();
            this.Rol = new HashSet<Rol>();
            this.RolMenu = new HashSet<RolMenu>();
            this.Almacen = new HashSet<Almacen>();
            this.AlmacenUbicacion = new HashSet<AlmacenUbicacion>();
            this.Articulo = new HashSet<Articulo>();
            this.ArticuloCaracteristica = new HashSet<ArticuloCaracteristica>();
            this.ArticuloPrecio = new HashSet<ArticuloPrecio>();
            this.Caracteristica = new HashSet<Caracteristica>();
            this.Categoria = new HashSet<Categoria>();
            this.Coleccion = new HashSet<Coleccion>();
            this.Color = new HashSet<Color>();
            this.Divisa = new HashSet<Divisa>();
            this.Estatus = new HashSet<Estatus>();
            this.Factura = new HashSet<Factura>();
            this.FacturaConcepto = new HashSet<FacturaConcepto>();
            this.LogModificacion = new HashSet<LogModificacion>();
            this.Marca = new HashSet<Marca>();
            this.Mensajeria = new HashSet<Mensajeria>();
            this.Presentacion = new HashSet<Presentacion>();
            this.Proveedor = new HashSet<Proveedor>();
            this.ProveedorContacto = new HashSet<ProveedorContacto>();
            this.RazonSocial = new HashSet<RazonSocial>();
            this.Ruta = new HashSet<Ruta>();
            this.SubCategoria = new HashSet<SubCategoria>();
            this.Sucursal = new HashSet<Sucursal>();
            this.Talla = new HashSet<Talla>();
            this.TipoAlmacen = new HashSet<TipoAlmacen>();
            this.TipoArticulo = new HashSet<TipoArticulo>();
            this.TipoArticuloCaracteristica = new HashSet<TipoArticuloCaracteristica>();
            this.TipoEstatus = new HashSet<TipoEstatus>();
            this.TipoImporte = new HashSet<TipoImporte>();
            this.TipoLogin = new HashSet<TipoLogin>();
            this.TipoPermiso = new HashSet<TipoPermiso>();
            this.TipoSucursal = new HashSet<TipoSucursal>();
            this.TipoUbicacion = new HashSet<TipoUbicacion>();
            this.TipoUsuarioSucursal = new HashSet<TipoUsuarioSucursal>();
            this.Ubicacion = new HashSet<Ubicacion>();
            this.Usuario1 = new HashSet<Usuario>();
            this.UsuarioProvider = new HashSet<UsuarioProvider>();
            this.UsuarioProvider1 = new HashSet<UsuarioProvider>();
            this.UsuarioRol = new HashSet<UsuarioRol>();
            this.UsuarioRol1 = new HashSet<UsuarioRol>();
            this.UsuarioSucursal = new HashSet<UsuarioSucursal>();
            this.UsuarioSucursal1 = new HashSet<UsuarioSucursal>();
            this.ValorCaracteristica = new HashSet<ValorCaracteristica>();
            this.Vista = new HashSet<Vista>();
        }
    
        public decimal idUsuario { get; set; }
        public decimal idTipoLogin { get; set; }
        public string nombreUsuario { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public decimal idUsuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<Empresa> Empresa { get; set; }
        public virtual ICollection<Icono> Icono { get; set; }
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual ICollection<Rol> Rol { get; set; }
        public virtual ICollection<RolMenu> RolMenu { get; set; }
        public virtual ICollection<Almacen> Almacen { get; set; }
        public virtual ICollection<AlmacenUbicacion> AlmacenUbicacion { get; set; }
        public virtual ICollection<Articulo> Articulo { get; set; }
        public virtual ICollection<ArticuloCaracteristica> ArticuloCaracteristica { get; set; }
        public virtual ICollection<ArticuloPrecio> ArticuloPrecio { get; set; }
        public virtual ICollection<Caracteristica> Caracteristica { get; set; }
        public virtual ICollection<Categoria> Categoria { get; set; }
        public virtual ICollection<Coleccion> Coleccion { get; set; }
        public virtual ICollection<Color> Color { get; set; }
        public virtual ICollection<Divisa> Divisa { get; set; }
        public virtual ICollection<Estatus> Estatus { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual ICollection<FacturaConcepto> FacturaConcepto { get; set; }
        public virtual ICollection<LogModificacion> LogModificacion { get; set; }
        public virtual ICollection<Marca> Marca { get; set; }
        public virtual ICollection<Mensajeria> Mensajeria { get; set; }
        public virtual ICollection<Presentacion> Presentacion { get; set; }
        public virtual ICollection<Proveedor> Proveedor { get; set; }
        public virtual ICollection<ProveedorContacto> ProveedorContacto { get; set; }
        public virtual ICollection<RazonSocial> RazonSocial { get; set; }
        public virtual ICollection<Ruta> Ruta { get; set; }
        public virtual ICollection<SubCategoria> SubCategoria { get; set; }
        public virtual ICollection<Sucursal> Sucursal { get; set; }
        public virtual ICollection<Talla> Talla { get; set; }
        public virtual ICollection<TipoAlmacen> TipoAlmacen { get; set; }
        public virtual ICollection<TipoArticulo> TipoArticulo { get; set; }
        public virtual ICollection<TipoArticuloCaracteristica> TipoArticuloCaracteristica { get; set; }
        public virtual ICollection<TipoEstatus> TipoEstatus { get; set; }
        public virtual ICollection<TipoImporte> TipoImporte { get; set; }
        public virtual ICollection<TipoLogin> TipoLogin { get; set; }
        public virtual ICollection<TipoPermiso> TipoPermiso { get; set; }
        public virtual ICollection<TipoSucursal> TipoSucursal { get; set; }
        public virtual ICollection<TipoUbicacion> TipoUbicacion { get; set; }
        public virtual ICollection<TipoUsuarioSucursal> TipoUsuarioSucursal { get; set; }
        public virtual ICollection<Ubicacion> Ubicacion { get; set; }
        public virtual TipoLogin TipoLogin1 { get; set; }
        public virtual ICollection<Usuario> Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual ICollection<UsuarioProvider> UsuarioProvider { get; set; }
        public virtual ICollection<UsuarioProvider> UsuarioProvider1 { get; set; }
        public virtual ICollection<UsuarioRol> UsuarioRol { get; set; }
        public virtual ICollection<UsuarioRol> UsuarioRol1 { get; set; }
        public virtual ICollection<UsuarioSucursal> UsuarioSucursal { get; set; }
        public virtual ICollection<UsuarioSucursal> UsuarioSucursal1 { get; set; }
        public virtual ICollection<ValorCaracteristica> ValorCaracteristica { get; set; }
        public virtual ICollection<Vista> Vista { get; set; }
    }
}
