//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hoond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioSucursal
    {
        public decimal idSucursal { get; set; }
        public decimal idUsuario { get; set; }
        public decimal idTipoUsuarioSucursal { get; set; }
        public decimal idUsuario_alta { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public bool activo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoUsuarioSucursal TipoUsuarioSucursal { get; set; }
    }
}
